/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlayerStats = IDL.Record({
  'focus' : IDL.Nat,
  'aura' : IDL.Nat,
  'speed' : IDL.Nat,
  'strength' : IDL.Nat,
  'endurance' : IDL.Nat,
  'intelligence' : IDL.Nat,
});
export const PlayerProfile = IDL.Record({
  'xp' : IDL.Nat,
  'username' : IDL.Text,
  'level' : IDL.Nat,
  'stats' : PlayerStats,
  'achievements' : IDL.Vec(IDL.Nat),
  'skillPoints' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addXP' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'getPlayerProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerPlayer' : IDL.Func([IDL.Text], [], []),
  'unlockAchievement' : IDL.Func([IDL.Nat], [], []),
  'updateStats' : IDL.Func([PlayerStats], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlayerStats = IDL.Record({
    'focus' : IDL.Nat,
    'aura' : IDL.Nat,
    'speed' : IDL.Nat,
    'strength' : IDL.Nat,
    'endurance' : IDL.Nat,
    'intelligence' : IDL.Nat,
  });
  const PlayerProfile = IDL.Record({
    'xp' : IDL.Nat,
    'username' : IDL.Text,
    'level' : IDL.Nat,
    'stats' : PlayerStats,
    'achievements' : IDL.Vec(IDL.Nat),
    'skillPoints' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addXP' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'getPlayerProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerPlayer' : IDL.Func([IDL.Text], [], []),
    'unlockAchievement' : IDL.Func([IDL.Nat], [], []),
    'updateStats' : IDL.Func([PlayerStats], [], []),
  });
};

export const init = ({ IDL }) => { return []; };