/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActiveChallenge {
  'day' : bigint,
  'challengeId' : string,
  'startDate' : string,
}
export interface CategoryXP {
  'focus' : bigint,
  'discipline' : bigint,
  'mindset' : bigint,
  'martial' : bigint,
  'fitness' : bigint,
  'intelligence' : bigint,
}
export interface PlayerProfile {
  'xp' : bigint,
  'age' : bigint,
  'categoryXP' : CategoryXP,
  'weight' : string,
  'completedHabits' : Array<string>,
  'height' : string,
  'fitnessLevel' : string,
  'username' : string,
  'goal' : string,
  'martialArtsLevel' : bigint,
  'completedMissions' : Array<string>,
  'activeChallenge' : [] | [ActiveChallenge],
  'level' : bigint,
  'stats' : PlayerStats,
  'achievements' : Array<bigint>,
  'weeklyWorkouts' : Array<string>,
  'gender' : string,
  'skillPoints' : bigint,
  'martialArtsXP' : bigint,
  'bodyType' : string,
}
export interface PlayerStats {
  'focus' : bigint,
  'aura' : bigint,
  'speed' : bigint,
  'strength' : bigint,
  'endurance' : bigint,
  'intelligence' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'advanceChallengeDay' : ActorMethod<[], undefined>,
  'applySelfPenalty' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardCameraXP' : ActorMethod<[bigint, string], undefined>,
  'completeHabit' : ActorMethod<[string, string], undefined>,
  'completeMission' : ActorMethod<[string, string, bigint], undefined>,
  'completeWorkout' : ActorMethod<[string, bigint, string], undefined>,
  'deletePlayer' : ActorMethod<[], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHabitCompletions' : ActorMethod<[], Array<string>>,
  'getLeaderboard' : ActorMethod<[], Array<PlayerProfile>>,
  'getMissionCompletions' : ActorMethod<[], Array<string>>,
  'getPlayerProfile' : ActorMethod<[], [] | [PlayerProfile]>,
  'getPublicProfile' : ActorMethod<[Principal], [] | [PlayerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerPlayer' : ActorMethod<
    [string, bigint, string, string, string, string, string, string],
    undefined
  >,
  'resetPlayerProgress' : ActorMethod<[], undefined>,
  'startChallenge' : ActorMethod<[string, string], undefined>,
  'unlockAchievement' : ActorMethod<[bigint], undefined>,
  'updateMartialArtsXP' : ActorMethod<[bigint], undefined>,
  'updateStats' : ActorMethod<[PlayerStats], undefined>,
  'xpToLevel' : ActorMethod<[bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];