/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CategoryXP = IDL.Record({
  'focus' : IDL.Nat,
  'discipline' : IDL.Nat,
  'mindset' : IDL.Nat,
  'martial' : IDL.Nat,
  'fitness' : IDL.Nat,
  'intelligence' : IDL.Nat,
});
export const ActiveChallenge = IDL.Record({
  'day' : IDL.Nat,
  'challengeId' : IDL.Text,
  'startDate' : IDL.Text,
});
export const PlayerStats = IDL.Record({
  'focus' : IDL.Nat,
  'aura' : IDL.Nat,
  'speed' : IDL.Nat,
  'strength' : IDL.Nat,
  'endurance' : IDL.Nat,
  'intelligence' : IDL.Nat,
});
export const PlayerProfile = IDL.Record({
  'xp' : IDL.Nat,
  'age' : IDL.Nat,
  'categoryXP' : CategoryXP,
  'weight' : IDL.Text,
  'completedHabits' : IDL.Vec(IDL.Text),
  'height' : IDL.Text,
  'fitnessLevel' : IDL.Text,
  'username' : IDL.Text,
  'goal' : IDL.Text,
  'martialArtsLevel' : IDL.Nat,
  'completedMissions' : IDL.Vec(IDL.Text),
  'activeChallenge' : IDL.Opt(ActiveChallenge),
  'level' : IDL.Nat,
  'stats' : PlayerStats,
  'achievements' : IDL.Vec(IDL.Nat),
  'weeklyWorkouts' : IDL.Vec(IDL.Text),
  'gender' : IDL.Text,
  'skillPoints' : IDL.Nat,
  'martialArtsXP' : IDL.Nat,
  'bodyType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'advanceChallengeDay' : IDL.Func([], [], []),
  'applySelfPenalty' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardCameraXP' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'completeHabit' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'completeMission' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'completeWorkout' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'deletePlayer' : IDL.Func([], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHabitCompletions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'getMissionCompletions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPlayerProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
  'getPublicProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerPlayer' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'resetPlayerProgress' : IDL.Func([], [], []),
  'startChallenge' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'unlockAchievement' : IDL.Func([IDL.Nat], [], []),
  'updateMartialArtsXP' : IDL.Func([IDL.Nat], [], []),
  'updateStats' : IDL.Func([PlayerStats], [], []),
  'xpToLevel' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CategoryXP = IDL.Record({
    'focus' : IDL.Nat,
    'discipline' : IDL.Nat,
    'mindset' : IDL.Nat,
    'martial' : IDL.Nat,
    'fitness' : IDL.Nat,
    'intelligence' : IDL.Nat,
  });
  const ActiveChallenge = IDL.Record({
    'day' : IDL.Nat,
    'challengeId' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const PlayerStats = IDL.Record({
    'focus' : IDL.Nat,
    'aura' : IDL.Nat,
    'speed' : IDL.Nat,
    'strength' : IDL.Nat,
    'endurance' : IDL.Nat,
    'intelligence' : IDL.Nat,
  });
  const PlayerProfile = IDL.Record({
    'xp' : IDL.Nat,
    'age' : IDL.Nat,
    'categoryXP' : CategoryXP,
    'weight' : IDL.Text,
    'completedHabits' : IDL.Vec(IDL.Text),
    'height' : IDL.Text,
    'fitnessLevel' : IDL.Text,
    'username' : IDL.Text,
    'goal' : IDL.Text,
    'martialArtsLevel' : IDL.Nat,
    'completedMissions' : IDL.Vec(IDL.Text),
    'activeChallenge' : IDL.Opt(ActiveChallenge),
    'level' : IDL.Nat,
    'stats' : PlayerStats,
    'achievements' : IDL.Vec(IDL.Nat),
    'weeklyWorkouts' : IDL.Vec(IDL.Text),
    'gender' : IDL.Text,
    'skillPoints' : IDL.Nat,
    'martialArtsXP' : IDL.Nat,
    'bodyType' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'advanceChallengeDay' : IDL.Func([], [], []),
    'applySelfPenalty' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardCameraXP' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'completeHabit' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'completeMission' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'completeWorkout' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'deletePlayer' : IDL.Func([], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHabitCompletions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'getMissionCompletions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPlayerProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
    'getPublicProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerPlayer' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'resetPlayerProgress' : IDL.Func([], [], []),
    'startChallenge' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'unlockAchievement' : IDL.Func([IDL.Nat], [], []),
    'updateMartialArtsXP' : IDL.Func([IDL.Nat], [], []),
    'updateStats' : IDL.Func([PlayerStats], [], []),
    'xpToLevel' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };