/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CategoryXP {
    focus: bigint;
    discipline: bigint;
    mindset: bigint;
    martial: bigint;
    fitness: bigint;
    intelligence: bigint;
}
export interface ActiveChallenge {
    day: bigint;
    challengeId: string;
    startDate: string;
}
export interface PlayerStats {
    focus: bigint;
    aura: bigint;
    speed: bigint;
    strength: bigint;
    endurance: bigint;
    intelligence: bigint;
}
export interface PlayerProfile {
    xp: bigint;
    age: bigint;
    categoryXP: CategoryXP;
    weight: string;
    completedHabits: Array<string>;
    height: string;
    fitnessLevel: string;
    username: string;
    goal: string;
    martialArtsLevel: bigint;
    completedMissions: Array<string>;
    activeChallenge?: ActiveChallenge;
    level: bigint;
    stats: PlayerStats;
    achievements: Array<bigint>;
    weeklyWorkouts: Array<string>;
    gender: string;
    skillPoints: bigint;
    martialArtsXP: bigint;
    bodyType: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    advanceChallengeDay(): Promise<void>;
    applySelfPenalty(xpLoss: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    awardCameraXP(xpAmount: bigint, category: string): Promise<void>;
    completeHabit(habitId: string, date: string): Promise<void>;
    completeMission(missionId: string, category: string, xpReward: bigint): Promise<void>;
    completeWorkout(workoutId: string, xpReward: bigint, category: string): Promise<void>;
    deletePlayer(): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getHabitCompletions(): Promise<Array<string>>;
    getLeaderboard(): Promise<Array<PlayerProfile>>;
    getMissionCompletions(): Promise<Array<string>>;
    getPlayerProfile(): Promise<PlayerProfile | null>;
    getPublicProfile(player: Principal): Promise<PlayerProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerPlayer(username: string, age: bigint, gender: string, goal: string, fitnessLevel: string, bodyType: string, weight: string, height: string): Promise<void>;
    resetPlayerProgress(): Promise<void>;
    startChallenge(challengeId: string, startDate: string): Promise<void>;
    unlockAchievement(badgeId: bigint): Promise<void>;
    updateMartialArtsXP(xpToAdd: bigint): Promise<void>;
    updateStats(newStats: PlayerStats): Promise<void>;
    xpToLevel(xp: bigint): Promise<bigint>;
}
import type { ActiveChallenge as _ActiveChallenge, CategoryXP as _CategoryXP, PlayerProfile as _PlayerProfile, PlayerStats as _PlayerStats, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async advanceChallengeDay(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.advanceChallengeDay();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.advanceChallengeDay();
            return result;
        }
    }
    async applySelfPenalty(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applySelfPenalty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applySelfPenalty(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async awardCameraXP(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.awardCameraXP(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.awardCameraXP(arg0, arg1);
            return result;
        }
    }
    async completeHabit(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeHabit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeHabit(arg0, arg1);
            return result;
        }
    }
    async completeMission(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeMission(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeMission(arg0, arg1, arg2);
            return result;
        }
    }
    async completeWorkout(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeWorkout(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeWorkout(arg0, arg1, arg2);
            return result;
        }
    }
    async deletePlayer(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlayer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlayer();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabitCompletions(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabitCompletions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabitCompletions();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<PlayerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMissionCompletions(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMissionCompletions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMissionCompletions();
            return result;
        }
    }
    async getPlayerProfile(): Promise<PlayerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicProfile(arg0: Principal): Promise<PlayerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerPlayer(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPlayer(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPlayer(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async resetPlayerProgress(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPlayerProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPlayerProgress();
            return result;
        }
    }
    async startChallenge(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startChallenge(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startChallenge(arg0, arg1);
            return result;
        }
    }
    async unlockAchievement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockAchievement(arg0);
            return result;
        }
    }
    async updateMartialArtsXP(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMartialArtsXP(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMartialArtsXP(arg0);
            return result;
        }
    }
    async updateStats(arg0: PlayerStats): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStats(arg0);
            return result;
        }
    }
    async xpToLevel(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.xpToLevel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.xpToLevel(arg0);
            return result;
        }
    }
}
function from_candid_PlayerProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerProfile): PlayerProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ActiveChallenge]): ActiveChallenge | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerProfile]): PlayerProfile | null {
    return value.length === 0 ? null : from_candid_PlayerProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    age: bigint;
    categoryXP: _CategoryXP;
    weight: string;
    completedHabits: Array<string>;
    height: string;
    fitnessLevel: string;
    username: string;
    goal: string;
    martialArtsLevel: bigint;
    completedMissions: Array<string>;
    activeChallenge: [] | [_ActiveChallenge];
    level: bigint;
    stats: _PlayerStats;
    achievements: Array<bigint>;
    weeklyWorkouts: Array<string>;
    gender: string;
    skillPoints: bigint;
    martialArtsXP: bigint;
    bodyType: string;
}): {
    xp: bigint;
    age: bigint;
    categoryXP: CategoryXP;
    weight: string;
    completedHabits: Array<string>;
    height: string;
    fitnessLevel: string;
    username: string;
    goal: string;
    martialArtsLevel: bigint;
    completedMissions: Array<string>;
    activeChallenge?: ActiveChallenge;
    level: bigint;
    stats: PlayerStats;
    achievements: Array<bigint>;
    weeklyWorkouts: Array<string>;
    gender: string;
    skillPoints: bigint;
    martialArtsXP: bigint;
    bodyType: string;
} {
    return {
        xp: value.xp,
        age: value.age,
        categoryXP: value.categoryXP,
        weight: value.weight,
        completedHabits: value.completedHabits,
        height: value.height,
        fitnessLevel: value.fitnessLevel,
        username: value.username,
        goal: value.goal,
        martialArtsLevel: value.martialArtsLevel,
        completedMissions: value.completedMissions,
        activeChallenge: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.activeChallenge)),
        level: value.level,
        stats: value.stats,
        achievements: value.achievements,
        weeklyWorkouts: value.weeklyWorkouts,
        gender: value.gender,
        skillPoints: value.skillPoints,
        martialArtsXP: value.martialArtsXP,
        bodyType: value.bodyType
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerProfile>): Array<PlayerProfile> {
    return value.map((x)=>from_candid_PlayerProfile_n6(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
